In [12]:
#In this code, Random Forest is implemented on Blood pressure abnomality data of patients.

import pandas as pd

In [13]:
#importing data from local file
bp_data = pd.read_csv(r'C:\Users\Siddharth Tripathi\Documents\Patient_with_abnormal_bloodpressure.csv')

In [14]:
bp_data.head()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0

In [15]:
#shape of data - 2000 rows and 15 columns
bp_data.shape

(2000, 15)

In [16]:
#checking the null values in our data set
bp_data.isnull().sum()

Patient_Number                      0
Blood_Pressure_Abnormality          0
Level_of_Hemoglobin                 0
Genetic_Pedigree_Coefficient       92
Age                                 0
BMI                                 0
Sex                                 0
Pregnancy                        1558
Smoking                             0
Physical_activity                   0
salt_content_in_the_diet            0
alcohol_consumption_per_day       242
Level_of_Stress                     0
Chronic_kidney_disease              0
Adrenal_and_thyroid_disorders       0
dtype: int64

In [17]:
#data cleaning
bp_data.Genetic_Pedigree_Coefficient=bp_data.Genetic_Pedigree_Coefficient.fillna(0)
bp_data.Pregnancy = bp_data.Pregnancy.fillna(0)
bp_data.alcohol_consumption_per_day = bp_data.alcohol_consumption_per_day.fillna(0)

In [18]:
bp_data.isnull().sum()

Patient_Number                   0
Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

In [19]:
#Describing data

#bp_data = bp_data.iloc[:,1:15]

bp_data.describe(include='all')

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,1000.500000,0.493500,11.710035,0.472055,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,220.636500,2.012500,0.5050,0.443500
std,577.494589,0.500083,2.186701,0.303221,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,157.614106,0.823822,0.5001,0.496922
min,1.000000,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,500.750000,0.000000,10.147500,0.200000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,79.000000,1.000000,0.0000,0.000000
50%,1000.500000,0.000000,11.330000,0.470000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,212.500000,2.000000,1.0000,0.000000
75%,1500.250000,1.000000,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000
max,2000.000000,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

In [20]:
#data pre processing. Converting features into categorical features

bp_data.Blood_Pressure_Abnormality= bp_data.Blood_Pressure_Abnormality.astype('category')
bp_data.Sex = bp_data.Sex.astype('category')
bp_data.Smoking = bp_data.Smoking.astype('category')
bp_data.Pregnancy = bp_data.Pregnancy.astype('category')
bp_data.Level_of_Stress = bp_data.Level_of_Stress.astype('category')
bp_data.Chronic_kidney_disease = bp_data.Chronic_kidney_disease.astype('category')
bp_data.Adrenal_and_thyroid_disorders = bp_data.Adrenal_and_thyroid_disorders.astype('category')

In [21]:
#importing random forest classifier from sklearn library

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [22]:
#splitting data into target variable and independent feature

bp_data_X = bp_data.iloc[:,2:15]
bp_data_Y = bp_data.iloc[:,1]

bp_data_X.head()

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,11.28,0.90,34,23,1,1.0,0,45961,48071,0.0,2,1,1
1,9.75,0.23,54,33,1,0.0,0,26106,25333,205.0,3,0,0
2,10.79,0.91,70,49,0,0.0,0,9995,29465,67.0,2,1,0
3,11.00,0.43,71,50,0,0.0,0,10635,7439,242.0,1,1,0
4,14.17,0.83,52,19,0,0.0,0,15619,49644,397.0,2,0,0

In [23]:
#splitting data into training and testing

bp_data_X_train,bp_data_X_test, bp_data_Y_train, bp_data_Y_test = train_test_split(bp_data_X,bp_data_Y,test_size=0.2,random_state=80)

In [28]:
# creating instance of random forest classifier. Taking n_estimators (number of trees to be their in our forest) = 100
rndm_fr = RandomForestClassifier(n_estimators=100)

In [29]:
#using fit method, training our model on train data.
rndm_fr.fit(bp_data_X_train,bp_data_Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [30]:
#predicting values for the test data x on our model.
predic_value= rndm_fr.predict(bp_data_X_test)

In [31]:
predic_value

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0], dtype=int64)

In [32]:
#plotting the confusion matrix for the predicted values by our model.

conf_mat = confusion_matrix(predic_value, bp_data_Y_test)
conf_mat

array([[182,  30],
       [ 23, 165]], dtype=int64)

In [33]:
#calculating the accuracy through confusion matrix.

bp_acc=conf_mat.diagonal().sum()/conf_mat.sum()*100
bp_acc

86.75

In [34]:
#calculating the feature importance in our training data.
#This is one to one mapping meaning first value is --> first column
#Higher the value, more the importance. All values add up to 1.0

rndm_fr.feature_importances_

array([0.22873509, 0.22145407, 0.05725046, 0.05238786, 0.01860609,
       0.00680541, 0.01053635, 0.06318109, 0.0670861 , 0.05893418,
       0.01651764, 0.12590639, 0.07259926])

In [35]:
bp_data_X_train.columns

Index(['Level_of_Hemoglobin', 'Genetic_Pedigree_Coefficient', 'Age', 'BMI',
       'Sex', 'Pregnancy', 'Smoking', 'Physical_activity',
       'salt_content_in_the_diet', 'alcohol_consumption_per_day',
       'Level_of_Stress', 'Chronic_kidney_disease',
       'Adrenal_and_thyroid_disorders'],
      dtype='object')

In [36]:
list_feat = list(rndm_fr.feature_importances_)

In [37]:
# just to display the feature importance list in a better way
feature_importance_rf = pd.DataFrame({'Feature_Name':bp_data_X_train.columns,'Feature_importance':list_feat})
feature_importance_rf

                     Feature_Name  Feature_importance
0             Level_of_Hemoglobin            0.228735
1    Genetic_Pedigree_Coefficient            0.221454
2                             Age            0.057250
3                             BMI            0.052388
4                             Sex            0.018606
5                       Pregnancy            0.006805
6                         Smoking            0.010536
7               Physical_activity            0.063181
8        salt_content_in_the_diet            0.067086
9     alcohol_consumption_per_day            0.058934
10                Level_of_Stress            0.016518
11         Chronic_kidney_disease            0.125906
12  Adrenal_and_thyroid_disorders            0.072599

In [38]:
#arranging in ascending order
feature_importance_rf = feature_importance_rf.sort_values('Feature_importance', ascending=False)
feature_importance_rf

                     Feature_Name  Feature_importance
0             Level_of_Hemoglobin            0.228735
1    Genetic_Pedigree_Coefficient            0.221454
11         Chronic_kidney_disease            0.125906
12  Adrenal_and_thyroid_disorders            0.072599
8        salt_content_in_the_diet            0.067086
7               Physical_activity            0.063181
9     alcohol_consumption_per_day            0.058934
2                             Age            0.057250
3                             BMI            0.052388
4                             Sex            0.018606
10                Level_of_Stress            0.016518
6                         Smoking            0.010536
5                       Pregnancy            0.006805

In [39]:
# from termcolor import colored #this is to print different color output

def enter_input():
    global data_frame1
    Level_of_Hemoglobin = eval(input("Enter you Hemoglobin Level::"))
    Genetic_Pedigree_Coefficient = eval(input("Enter your Genetic Pedigree Coefficients"))
    Age = eval(input("Enter your Age"))
    BMI = eval(input("Enter you Bio Mass Index"))
    Sex = eval(input("Enter you sex, 0 being Male and 1 being female"))
    Pregnancy=eval(input("Enter 1 if Pregnant or enter 0"))
    Smoking=eval(input("Enter 1 if you smoke or enter 0"))
    Physical_activity=eval(input("Enter Physical activity calorie burnt/day"))
    salt_content_in_diet = eval(input("Enter salt content in micro-gram"))
    alchohol_consumption_per_day = eval(input("Enter alchohol consumption per day in ml"))
    Level_of_Stress = eval(input("Enter Level of Stress in 1-3, 1 being low 3 being high"))
    Chronic_kidney_disease=eval(input("Enter 1 if having chronic kidney disease or enter 0"))
    Adrenal_and_thyroid_disorders=eval(input("Enter 1 if having disorder or enter 0"))
    data_frame1 = pd.DataFrame({"Level_of_Hemoglobin":[Level_of_Hemoglobin],"Genetic_Pedigree_Coefficient":[Genetic_Pedigree_Coefficient],
                               "Age":[Age],"BMI":[BMI],"Sex":[Sex],"Pregnancy":[Pregnancy],"Smoking":[Smoking],"Physical_activity":[Physical_activity],
                                "salt_content_in_diet":[salt_content_in_diet],"alchohol_consumption_per_day":[alchohol_consumption_per_day],
                                "Level_of_Stress":[Level_of_Stress], "Chronic_kidney_disease":[Chronic_kidney_disease],
                                "Adrenal_and_thyroid_disorders":[Adrenal_and_thyroid_disorders]})
    
    global predict_value1
    predict_value1 = rndm_fr.predict(data_frame1)
    global probabilistic_value1
    probabilistic_value1 = rndm_fr.predict_proba(data_frame1)
#     print(colored("---------------------",'blue'))
#     print(colored("---------------------",'red'))
#     print(colored("---------------------",'yellow'))
    if predict_value1 == 0:
        print("----- Chances of Abnormal BP --Low Risk")
        print("--Probability of Having normal Bp",probabilistic_value1[0][0])
    else:
        print("-----Chances of Abnormal BP -- High Risk")
        print("--Probability of Having abnormal Bp",probabilistic_value1[0][1])

In [40]:
enter_input()

Enter you Hemoglobin Level::11
Enter your Genetic Pedigree Coefficients0
Enter your Age26
Enter you Bio Mass Index19
Enter you sex, 0 being Male and 1 being female0
Enter 1 if Pregnant or enter 00
Enter 1 if you smoke or enter 01
Enter Physical activity calorie burnt/day200
Enter salt content in micro-gram12
Enter alchohol consumption per day in ml150
Enter Level of Stress in 1-3, 1 being low 3 being high2
Enter 1 if having chronic kidney disease or enter 00
Enter 1 if having disorder or enter 00
----- Chances of Abnormal BP --Low Risk
--Probability of Having normal Bp 0.56